-- Perfume Shop - Initial Schema
--
-- All 18 JPA entities. Every CHECK below is generated from an @Enumerated
-- column and matches what Hibernate creates.
--
-- RULE: adding an enum value needs a new migration (V1_0_1__...) that updates
-- the affected CHECK. Never edit this file once applied.
--
-- Enum CHECKs:
--   Governorate -> customers, customer_orders, guest_orders, delivery_fees
--   PerfumeType -> perfumes
--   PerfumeSize -> item_prices, order_items
--   OrderStatus, CancellationSource -> orders
--   DiscountType -> coupons
--   NotificationType -> notifications
--   UserType -> user_notifications, device_tokens, password_reset_codes
--   DeviceType -> device_tokens

-- ========== Admins & Customers ==========

CREATE TABLE admins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    email varchar(255) NOT NULL,
    first_name varchar(50) NOT NULL,
    last_name varchar(50) NOT NULL,
    password varchar(255) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT uk_admins_email UNIQUE (email)
);

CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(255) NOT NULL,
    alternative_phone_number varchar(255),
    created_at timestamp(6) NOT NULL,
    email varchar(255) NOT NULL,
    first_name varchar(255) NOT NULL,
    governorate varchar(255) NOT NULL,
    last_name varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    phone_number varchar(255) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT uk_customers_email UNIQUE (email),
    CONSTRAINT ck_customers_governorate CHECK (governorate IN ('AMMAN', 'ZARQA', 'IRBID', 'BALQA', 'MADABA', 'KARAK', 'JERASH', 'AJLOUN', 'MAFRAQ', 'TAFILAH', 'MAAN', 'AQABA'))
);

-- ========== Items / Perfumes ==========

CREATE TABLE items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    brand varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    name varchar(255) NOT NULL,
    updated_at timestamp(6),
    CONSTRAINT uk_items_name_brand UNIQUE (name, brand)
);

CREATE TABLE perfumes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    perfume_seasons varchar(255) NOT NULL,
    perfume_type varchar(255) NOT NULL,
    updated_at timestamp(6),
    item_id bigint NOT NULL,
    CONSTRAINT uk_perfumes_item UNIQUE (item_id),
    CONSTRAINT ck_perfumes_type CHECK (perfume_type IN ('FEMALE', 'MALE', 'UNISEX')),
    CONSTRAINT fk_perfumes_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE item_prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    effective_from timestamp(6) NOT NULL,
    effective_to timestamp(6),
    is_active boolean NOT NULL,
    notes text,
    perfume_size varchar(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    updated_at timestamp(6),
    item_id bigint NOT NULL,
    CONSTRAINT ck_item_prices_size CHECK (perfume_size IN ('SIZE_50', 'SIZE_100')),
    CONSTRAINT fk_item_prices_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE item_translations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    description text,
    locale varchar(5) NOT NULL,
    name varchar(255) NOT NULL,
    updated_at timestamp(6),
    item_id bigint NOT NULL,
    CONSTRAINT uk_item_translations_locale UNIQUE (item_id, locale),
    CONSTRAINT fk_item_translations_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE perfume_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    display_order integer NOT NULL,
    file_size bigint NOT NULL,
    image_data bytea NOT NULL,
    is_primary boolean NOT NULL,
    mime_type varchar(255) NOT NULL,
    updated_at timestamp(6),
    perfume_id bigint NOT NULL,
    CONSTRAINT fk_perfume_images_perfume FOREIGN KEY (perfume_id) REFERENCES perfumes (id)
);

-- ========== Orders ==========

CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cancellation_reason text,
    cancellation_source varchar(255),
    cancelled_at timestamp(6),
    delivered_at timestamp(6),
    notes text,
    order_date timestamp(6) NOT NULL,
    order_number varchar(255) NOT NULL,
    shipping_fee numeric(10,2) NOT NULL,
    status varchar(255) NOT NULL,
    total_price numeric(10,2) NOT NULL,
    CONSTRAINT uk_orders_number UNIQUE (order_number),
    CONSTRAINT ck_orders_cancellation_source CHECK (cancellation_source IN ('CUSTOMER', 'ADMIN')),
    CONSTRAINT ck_orders_status CHECK (status IN ('PENDING', 'PROCESSING', 'DELIVERED', 'CANCELLED'))
);

-- ========== Coupons ==========

CREATE TABLE coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    code varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    discount_type varchar(255) NOT NULL,
    discount_value numeric(10,2) NOT NULL,
    expiry_date timestamp(6) NOT NULL,
    max_usage integer,
    updated_at timestamp(6),
    usage_count integer NOT NULL,
    created_by_id bigint NOT NULL,
    CONSTRAINT uk_coupons_code UNIQUE (code),
    CONSTRAINT ck_coupons_discount_type CHECK (discount_type IN ('FIXED', 'PERCENTAGE')),
    CONSTRAINT fk_coupons_admin FOREIGN KEY (created_by_id) REFERENCES admins (id)
);

CREATE TABLE coupon_usages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    used_at timestamp(6) NOT NULL,
    coupon_id bigint NOT NULL,
    customer_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT uk_coupon_usages_customer UNIQUE (coupon_id, customer_id),
    CONSTRAINT fk_coupon_usages_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT fk_coupon_usages_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_coupon_usages_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    perfume_size varchar(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    item_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT ck_order_items_size CHECK (perfume_size IN ('SIZE_50', 'SIZE_100')),
    CONSTRAINT fk_order_items_item FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body varchar(255),
    created_at timestamp(6) NOT NULL,
    recipient varchar(255) NOT NULL,
    subject varchar(255) NOT NULL,
    type varchar(255) NOT NULL,
    coupon_id bigint,
    order_id bigint,
    CONSTRAINT ck_notifications_type CHECK (type IN ('EMAIL', 'PUSH')),
    CONSTRAINT fk_notifications_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT fk_notifications_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE TABLE customer_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(255) NOT NULL,
    alternative_phone_number varchar(255),
    created_at timestamp(6) NOT NULL,
    governorate varchar(255) NOT NULL,
    phone_number varchar(255) NOT NULL,
    coupon_id bigint,
    customer_id bigint NOT NULL,
    order_id bigint NOT NULL,
    CONSTRAINT uk_customer_orders_order UNIQUE (order_id),
    CONSTRAINT fk_customer_orders_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT fk_customer_orders_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT fk_customer_orders_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_customer_orders_governorate CHECK (governorate IN ('AMMAN', 'ZARQA', 'IRBID', 'BALQA', 'MADABA', 'KARAK', 'JERASH', 'AJLOUN', 'MAFRAQ', 'TAFILAH', 'MAAN', 'AQABA'))
);

CREATE TABLE guest_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address varchar(255) NOT NULL,
    alternative_phone_number varchar(255),
    claimed_at timestamp(6),
    created_at timestamp(6) NOT NULL,
    email varchar(255) NOT NULL,
    governorate varchar(255) NOT NULL,
    phone_number varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    claimed_by_customer_id bigint,
    order_id bigint NOT NULL,
    CONSTRAINT uk_guest_orders_order UNIQUE (order_id),
    CONSTRAINT fk_guest_orders_customer FOREIGN KEY (claimed_by_customer_id) REFERENCES customers (id),
    CONSTRAINT fk_guest_orders_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_guest_orders_governorate CHECK (governorate IN ('AMMAN', 'ZARQA', 'IRBID', 'BALQA', 'MADABA', 'KARAK', 'JERASH', 'AJLOUN', 'MAFRAQ', 'TAFILAH', 'MAAN', 'AQABA'))
);

-- ========== Delivery ==========

CREATE TABLE delivery_fees (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    governorate varchar(255) NOT NULL,
    shipping_fee numeric(10,2) NOT NULL,
    CONSTRAINT uk_delivery_fees_governorate UNIQUE (governorate),
    CONSTRAINT ck_delivery_fees_governorate CHECK (governorate IN ('AMMAN', 'ZARQA', 'IRBID', 'BALQA', 'MADABA', 'KARAK', 'JERASH', 'AJLOUN', 'MAFRAQ', 'TAFILAH', 'MAAN', 'AQABA'))
);

-- ========== Notifications ==========

CREATE TABLE user_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    received_at timestamp(6) NOT NULL,
    seen boolean NOT NULL,
    seen_at timestamp(6),
    user_id bigint NOT NULL,
    user_type varchar(255) NOT NULL,
    notification_id bigint NOT NULL,
    CONSTRAINT ck_user_notifications_user_type CHECK (user_type IN ('ADMIN', 'CUSTOMER')),
    CONSTRAINT fk_user_notifications_notification FOREIGN KEY (notification_id) REFERENCES notifications (id)
);

CREATE TABLE device_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    device_name varchar(255) NOT NULL,
    device_type varchar(255) NOT NULL,
    token varchar(255) NOT NULL,
    user_id bigint NOT NULL,
    user_type varchar(255) NOT NULL,
    CONSTRAINT uk_device_tokens_token UNIQUE (token),
    CONSTRAINT uk_device_tokens_user_device UNIQUE (user_id, user_type, device_name),
    CONSTRAINT ck_device_tokens_device_type CHECK (device_type IN ('WEB', 'ANDROID', 'IOS')),
    CONSTRAINT ck_device_tokens_user_type CHECK (user_type IN ('ADMIN', 'CUSTOMER'))
);

-- ========== Password Reset ==========

CREATE TABLE password_reset_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    expiry_date timestamp(6) NOT NULL,
    used boolean NOT NULL,
    user_id bigint NOT NULL,
    user_type varchar(255) NOT NULL,
    CONSTRAINT uk_password_reset_codes_code UNIQUE (code),
    CONSTRAINT ck_password_reset_codes_user_type CHECK (user_type IN ('ADMIN', 'CUSTOMER'))
);